services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8050:8080
  backend:
    build:
      context: ./olmonoko-backend/
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/postgres
      SITE_URL: http://localhost:8080
