DROP TABLE public_calendar_links;

CREATE TABLE public_calendar_links
(
	id TEXT PRIMARY KEY NOT NULL,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL UNIQUE,
	created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())*1000 NOT NULL
);
