CREATE TABLE api_keys (
	id 		UUID 	PRIMARY KEY	DEFAULT gen_random_uuid(),
	user_id 	INTEGER	NOT NULL	REFERENCES users(id) ON DELETE CASCADE,
	description	TEXT 	NOT NULL,
	scopes		TEXT[]	NOT NULL,
	revoked		BOOLEAN	NOT NULL 	DEFAULT FALSE,
	created_at 	BIGINT 	NOT NULL	DEFAULT EXTRACT(EPOCH FROM NOW())*1000,
	updated_at 	BIGINT 	NOT NULL	DEFAULT EXTRACT(EPOCH FROM NOW())*1000
);
